# -*- coding: utf-8 -*-
"""Day2 class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxoskYioqEXZxsgmXyY6GNjNL2j2QlsL
"""

import sqlite3
#py built in db lib,no pip install needed
import pandas as pd
#for data frame
import matplotlib.pyplot as plt
#plotting submodule for mathplot
import warnings
#supress non critical warning message
warnings.filterwarnings('ignore')
print("All libraries imported successfully")
print(f"pandas version: {pd.__version__}")
print(f"sqlite3 version: {sqlite3.version}")

df=pd.read_csv('/content/student_performance.csv')

print(f"Dataset loaded: {df.shape[0]} students, {df.shape[1]} columns")
print(f"Columns:{df.columns.tolist()}")
print("\nFirst 3 rows:")
df.head(3)

conn = sqlite3.connect('collage.db')
#connection to the db,and collage db would be created or opened if already present
cursor=conn.cursor()
df.to_sql(
    'student',
    conn,
    if_exists='replace',
    index=False
)
cursor.execute("SELECT COUNT(*) FROM student")
count=cursor.fetchone()[0]
#retrives the first result row
print(f"database'collage.db'created")
print(f"table'student'has{count}rows")

cursor.execute("PRAGMA table_info(students)")
colums_info=cursor.fetchall()
print("Table structure of students:")
print('Column Name'.ljust(25) + 'Data Type:'.ljust(12))
print("-"*38)
for col in colums_info:
  print(f"{col[1]:<25}{col[2]:<12}")

def run_query(sql,description=""):
  if description:
    print(f"\n{'='*55}")
    print(f" {description}")
    print(f"{'='*55}")
  result=pd.read_sql_query(sql,conn)
  print(result.to_string(index=False))
  return result
print("Helper function 'run-query' defined successfully")
print("Usage:reun_query(sql_string,description_label")

query1="""
SELECT student_id,name,department,math_score,attendance_percentage
FROM student
LIMIT 10
"""
result1=run_query(query1,"Query 1:First 10 student(SELECT+LIMIT)")

query1="""
SELECT student_id,name,department,math_score,attendance_percentage
FROM student
LIMIT 5 offset 25
"""
result1=run_query(query1,"Query 1:last 5 student(SELECT+LIMIT)")

query1="""
SELECT student_id,name,department,math_score,attendance_percentage
FROM student
ORDER BY student_id DESC
LIMIT 5
"""
result1=run_query(query1,"Query 1:Last 5 student(SELECT+LIMIT)")

query2="""
SELECT student_id,name,department,programming_score
FROM student
WHERE programming_score BETWEEN 50 AND 75
ORDER BY student_id
"""
result1=run_query(query1,"Query 1:The List of students between 50 and 75")

query1="""
SELECT name,math_score,science_score,programming_score,attendance_percentage
FROM student
WHERE department ='Computer Science'
ORDER BY programming_score DESC
"""
result1=run_query(query1,"Query 1:The List of students from CS dept")

query3="""
SELECT department From student
GROUP BY department
"""
result1=run_query(query3,"Query")

dept_data={

           'data_code':['cs','ec','mech','civil'],
           'dept_name':['Computer Science','Electronics','Mechanical','Civil'],
           'hod_name':['Dr sharma','Dr Ready','Dr patel','Dr Kumar'],
           'established':[1995,1945,1975,1986],
           'intake':[60,60,60,60]
}
dept_df=pd.DataFrame(dept_data)
dept_df.to_sql('departments',conn,if_exists='replace',index=False)
print("dept created dept table")
print(dept_df.to_string(index=False))
dept_map={
    'Computer Science':'CS',
    'Electronics':'EC',
    'Mechanical':'ME',
    'Civil':'CE'
}
df['department']=df['department'].map(dept_map)
df.to_sql('student',conn,if_exists='replace',index=False)
print("\nupdated students table with dept_code column")

query_join="""
SELECT
s.name,
s.math_score,
d.dept_name,
d.hod_name,
d.established
FROM student s
INNER JOIN departments AS d ON s.department=d.dept_name
ORDER BY s.math_score DESC
LIMIT 8
"""
result=run_query(query_join,"Query")